### PR TITLE
Add reset password to authentication page

### PR DESCRIPTION
**Pull request by danoro96**
To test:

1. Create an account
2. Click change password
3. Make sure you get an email with the password reset code
4. Create a new password
5. Make sure the new password works for logging in
6. Sign out from app

### CODE REVIEW

**Review by myNameIsNotJustin — CHANGES_REQUESTED** [review]
Screen Shot 2021-03-26 at 11 21 56 AM

Red border is bigger than textboxes when there is error. 
Error on fields doesn't clear

**Review by KalervoHyyppa — CHANGES_REQUESTED** [review]
For some reason, the error modal is hidden
image

**Review by myNameIsNotJustin — APPROVED** [review]
noice

**Review by KalervoHyyppa — CHANGES_REQUESTED** [review]
Signup isn't working for some emails

**Review by KalervoHyyppa — APPROVED** [review]
Gucci

**Pull request merged**
