### PR TITLE
HOFTIX **remove device does not have dashboard alert

### PR DESCRIPTION
**Pull request by robbieLew14**

### CODE REVIEW

**Review by KalervoHyyppa — CHANGES_REQUESTED** [review]
Instead of commenting out, check to see if mir map enabled. If not, then don't run function

**Review by davis-roboticmaterials — DISMISSED** [review]
Aprooved

**Review by KalervoHyyppa — DISMISSED** [review]
Works

**Review by KalervoHyyppa — APPROVED** [review]
Works

**Pull request merged**
